### Carregando arquivo CSV

In [6]:
uri = r"dados\csv.csv"



def conversor(uri):

    # Libraries
    import pandas as pd
    import numpy as np
    # import chardet # para buscar o encoding

    # with open(uri, 'rb') as csv_file:
    #     result = chardet.detect(csv_file.read())
    #     # print("The csv file encoding is",result['encoding'])


    names = np.arange(0, 16)

    df = pd.read_csv(uri, header=6, encoding='iso-8859-1', names=names)



    mylist = df.iloc[-1:].values.tolist().pop(0)

    
    df.columns = [str(i) for i in mylist]

    # Slice para excluir a última linha  
    df = df.iloc[:-1]

    # Slice para pegar todas as linhas e excluir as duas últimas colunas
    df = df.iloc[::,:-2]


    # df.columns = df.columns.map(lambda x: str(x))

    df = df.astype(float)

    df.iloc[-2, 1:] = df.iloc[-2, :-1].values

    df.iloc[-2, 0] = 0
    
    index = df.index.tolist()
    index.pop()
    df = df[1:]
    df.reset_index(drop=True, inplace=True)
    df.index = index
    return df

In [7]:
df = conversor(uri)

In [8]:
df

,0.0,750.0,1050.0,1250.0,1450.0,1550.0,1650.0,1750.0,1850.0,1950.0,2050.0,2150.0,2250.0,2350.0
125.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
110.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
100.000000,5.4,1.100000,2.500000,3.900000,1.400000,2.600000,6.400000,8.400000,9.900000,11.500000,12.100000,3.700000,0.0,0.0
95.000000,2.9,2.100000,4.900000,8.100000,7.500000,8.100000,7.300000,10.700000,12.800000,16.400000,18.799999,13.800000,0.0,0.0
90.000000,0.3,1.600000,2.000000,2.500000,1.400000,1.500000,2.500000,5.000000,5.000000,7.100000,7.800000,11.800000,0.0,0.0
80.000000,0.8,6.000000,7.500000,9.700000,5.600000,7.600000,12.300000,22.400000,20.299999,26.900000,23.299999,32.299999,0.1,0.0
70.000000,1.1,7.800000,12.700000,16.000000,8.700000,15.000000,25.400000,38.900002,26.600000,30.700001,22.200001,46.200001,0.4,0.0
60.000000,0.3,14.800000,26.299999,31.900000,17.600000,29.600000,45.000000,55.700001,35.599998,29.500000,20.299999,47.099998,1.7,0.0
50.000000,0.0,37.200001,66.099998,65.500000,29.400000,37.000000,50.000000,52.200001,35.099998,28.900000,19.400000,39.599998,4.0,0.0
40.000000,0.0,83.099998,167.699997,174.600006,61.400002,48.900002,62.099998,62.599998,41.799999,26.299999,16.100000,19.600000,4.4,0.0
30.000000,0.0,202.600006,345.399994,376.000000,125.400002,106.300003,83.099998,60.500000,35.400002,24.100000,14.500000,16.100000,5.6,0.0
20.000000,0.0,407.200012,366.899994,499.100006,200.000000,170.399994,102.000000,66.300003,34.400002,19.799999,11.200000,10.300000,5.0,0.0
10.000000,0.0,1578.699951,224.500000,275.000000,97.300003,57.099998,42.700001,28.400000,13.500000,7.500000,4.200000,2.800000,2.4,0.0
0.000000,0.1,30.600000,56.400002,71.300003,32.400002,26.799999,22.500000,17.799999,13.500000,9.800000,6.300000,3.300000,1.9,0.5